### ISSUE TITLE
Errors in the app

### ISSUE THREAD

**Issue by MrUnfunny** [govindmaheshwari2/zoom-example-app#1]
This throws a lot of errors when trying to build. hmssdk_flutter is specified to be 0.5.0 however the latest version itself is 0.4.1.

**Comment by govindmaheshwari2** [comment]
@MrUnfunny  0.5.0 is about to be release in 1-2 days.

**Comment by MrUnfunny** [comment]
Are other errors due to 0.5.0 version only?

**Comment by govindmaheshwari2** [comment]
yes they all depend on hmssdk_flutter: 0.5.0

**Comment by govindmaheshwari2** [comment]
@MrUnfunny hmssdk_flutter: 0.5.0 is out now. You can try running the app.
